---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-kafka:v1.0
    container_name: bungee-gum-kafka
    volumes:
      - /home/ghazi/playgroud/data-highway/shell/csv_to_parquet-data/input/:/app/data/kafka/input
      - /home/ghazi/playgroud/data-highway/shell/csv_to_parquet-data/output/:/app/data/kafka/output
      - /home/ghazi/playgroud/data-highway/shell/csv_to_parquet-data/processed/:/app/data/kafka/processed
      - /home/ghazi/workspace/data-highway/docker/data-highway/application.conf:/app/config/application.conf
      - /home/ghazi/workspace/data-highway/src/main/resources/logback.xml:/app/config/logback.xml
    entrypoint: [ "java", "-jar", "-Dconfig.file=/app/config/application.conf", "-Dlogback.configurationFile=/app/config/logback.xml", "/app/jar/data-highway-assembly-0.1.jar" ]
    network_mode: "host"