---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-app:v1.0
    ports:
      - "5555:5555"
    container_name: bungee-gum-app
    volumes:
      - /the-path-to-input-data-located-in-your-host-machine/:/app/data/input
      - /the-path-to-the-generated-output-in-your-host-machine/:/app/data/output
      - /the-path-to-your-log-file/log4j.properties:/app/config/log4j.properties
    entrypoint: ["java", "-cp", "/app/jar/data-highway-assembly-0.1.jar", "io.oss.data.highway.IOMain", "-Dlog4j.configuration=/app/config/log4j.properties"]
    network_mode: "host"