---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-app:v1.0
    ports:
      - "5555:5555"
    container_name: bungee-gum-app
    volumes:
    - /home/ghazi/playgroud/data-highway/shell/json_to_kafka-data/input/:/app/data/input
    - /home/ghazi/playgroud/data-highway/shell/json_to_kafka-data/output/:/app/data/output
    - /home/ghazi/workspace/data-highway/src/main/resources/log4j.properties:/app/config/log4j.properties
    entrypoint: ["java", "-cp", "/app/jar/data-highway-assembly-0.1.jar", "io.oss.data.highway.IOMain", "-Dlog4j.configuration=/app/config/log4j.properties"]
    network_mode: "host"