---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-kafka:v1.0
    container_name: bungee-gum-kafka
    volumes:
      - /the-path-to-input-data-located-in-your-host-machine/:/app/data/kafka/input
      - /the-path-to-the-generated-output-in-your-host-machine/:/app/data/kafka/output
      - /the-path-to-the-generated-processed-in-your-host-machine/:/app/data/kafka/processed
      - /the-path-to-your-config-file/application.conf:/app/config/application.conf
      - /the-path-to-your-log-file/logback.xml:/app/config/logback.xml
    entrypoint: [ "java", "-jar", "-Dconfig.file=/app/config/application.conf", "-Dlogback.configurationFile=/app/config/logback.xml", "/app/jar/data-highway-assembly-0.1.jar" ]
    network_mode: "host"