---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-app:v0.5-beta
    ports:
      - 5555:5555
    container_name: bungee-gum
    volumes:
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/input:/app/data/parquet/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/output:/app/data/parquet/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/processed:/app/data/parquet/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/orc/input:/app/data/orc/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/orc/output:/app/data/orc/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/orc/processed:/app/data/orc/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/json/input:/app/data/json/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/json/output:/app/data/json/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/json/processed:/app/data/json/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/avro/input:/app/data/avro/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/avro/output:/app/data/avro/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/avro/processed:/app/data/avro/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/csv/input:/app/data/csv/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/csv/output:/app/data/csv/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/csv/processed:/app/data/csv/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/input:/app/data/xlsx/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/output:/app/data/xlsx/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/processed:/app/data/xlsx/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/elasticsearch/input:/app/data/elasticsearch/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/elasticsearch/output:/app/data/elasticsearch/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/elasticsearch/processed:/app/data/elasticsearch/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/kafka/input:/app/data/kafka/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/kafka/output:/app/data/kafka/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/kafka/processed:/app/data/kafka/processed
      - /home/ghazi/workspace/data-highway/src/main/resources/log4j.properties:/app/config/log4j.properties
      - /home/ghazi/workspace/data-highway/src/main/resources/application.conf:/app/config/application.conf
    network_mode: "host"
    entrypoint: ["java", "-cp", "/app/jar/data-highway-0.5-beta.jar", "gn.oss.data.highway.IOMain", "-Dlog4j.configuration=/app/config/log4j.properties", "-Dconfig.file=/app/config/application.conf"]