---
version: '3.2'

services:

  app:
    build: .
    image: data-highway-app:v0.4-rc
    ports:
      - 5555:5555
    container_name: bungee-gum
    volumes:
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/input:/app/data/parquet/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/output:/app/data/parquet/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/parquet/processed:/app/data/parquet/processed
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/input:/app/data/xlsx/input
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/output:/app/data/xlsx/output
      - /home/ghazi/workspace/data-highway/src/test/resources/data/xlsx/processed:/app/data/xlsx/processed
      - /home/ghazi/workspace/data-highway/src/main/resources/log4j.properties:/app/config/log4j.properties
      - /home/ghazi/workspace/data-highway/src/main/resources/application.conf:/app/config/application.conf
    network_mode: "host"
    entrypoint: ["java", "-cp", "/app/jar/data-highway-0.4-rc.jar", "gn.oss.data.highway.IOMain", "-Dlog4j.configuration=/app/config/log4j.properties", "-Dconfig.file=/app/config/application.conf"]